export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/produk',
  PRODUCT: (slug: string) => `/produk/${slug}`,
  CATEGORY: (slug: string) => `/kategori/${slug}`,
  BRAND: (slug: string) => `/brand/${slug}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/pesanan',
  ORDER: (orderNumber: string) => `/pesanan/${orderNumber}`,
  FLASH_SALE: '/flash-sale',
  SEARCH: (q: string) => `/produk?q=${encodeURIComponent(q)}`,
  AUTH: {
    LOGIN: '/masuk',
    REGISTER: '/daftar',
    FORGOT_PASSWORD: '/lupa-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verifikasi-email',
  },
  ACCOUNT: {
    PROFILE: '/akun/profil',
    ADDRESSES: '/akun/alamat',
    WISHLIST: '/akun/wishlist',
    NOTIFICATIONS: '/akun/notifikasi',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    PRODUCTS: '/admin/produk',
    PRODUCT_ADD: '/admin/produk/tambah',
    PRODUCT_EDIT: (id: number) => `/admin/produk/${id}`,
    ORDERS: '/admin/pesanan',
    VOUCHERS: '/admin/voucher',
    BANNERS: '/admin/banner',
    CATEGORIES: '/admin/kategori',
    SETTINGS: '/admin/pengaturan',
    JUBELIO: '/admin/jubelio',
  },
} as const;
