import { type ProductListItem, type ProductDetail, type Category, type Banner, type FlashSale } from '@/types/product.types';

// ─── Categories ──────────────────────────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Hijab Voal', slug: 'hijab-voal', imageUrl: '/images/cat-hijab-voal.jpg', iconName: 'sparkles', productCount: 120, description: 'Koleksi hijab voal premium' },
  { id: 2, name: 'Gamis', slug: 'gamis', imageUrl: '/images/cat-gamis.jpg', iconName: 'layers', productCount: 85, description: 'Gamis modern dan elegan' },
  { id: 3, name: 'Mukena', slug: 'mukena', imageUrl: '/images/cat-mukena.jpg', iconName: 'heart', productCount: 40, description: 'Mukena cantik berkualitas' },
  { id: 4, name: 'Bergo', slug: 'bergo', imageUrl: '/images/cat-bergo.jpg', iconName: 'shopping-bag', productCount: 60, description: 'Bergo simple dan stylish' },
  { id: 5, name: 'Pashmina', slug: 'pashmina', imageUrl: '/images/cat-pashmina.jpg', iconName: 'star', productCount: 75, description: 'Pashmina lembut dan mewah' },
  { id: 6, name: 'Aksesoris', slug: 'aksesoris', imageUrl: '/images/cat-aksesoris.jpg', iconName: 'gem', productCount: 45, description: 'Aksesoris pelengkap penampilan' },
];

// ─── Banners ──────────────────────────────────────────────────────────────────

export const MOCK_BANNERS: Banner[] = [
  {
    id: 1,
    title: 'Koleksi Ramadhan 2026',
    subtitle: 'Elegansi dalam Kesederhanaan',
    description: 'Temukan koleksi eksklusif yang dirancang khusus untuk kenyamanan dan keanggunan gaya modern Anda.',
    imageUrl: 'https://images.unsplash.com/photo-1631947430066-48c30d57b943?w=1600&q=80',
    linkUrl: '/produk?collection=ramadhan',
    linkText: 'Belanja Sekarang',
    position: 'homepage_hero',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: 'Hijab Premium Terbaru',
    subtitle: 'Kualitas Terbaik untuk Anda',
    description: 'Material premium pilihan, nyaman dipakai sepanjang hari dengan berbagai pilihan warna.',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1600&q=80',
    linkUrl: '/produk?category=hijab-voal',
    linkText: 'Lihat Koleksi',
    position: 'homepage_hero',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    title: 'Flash Sale Akhir Bulan',
    subtitle: 'Diskon Hingga 50%',
    description: 'Jangan lewatkan penawaran terbatas ini! Stok sangat terbatas.',
    imageUrl: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1600&q=80',
    linkUrl: '/flash-sale',
    linkText: 'Lihat Flash Sale',
    position: 'homepage_hero',
    sortOrder: 3,
    isActive: true,
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────

const BASE_CATEGORY = { id: 1, name: 'Hijab Voal', slug: 'hijab-voal' };

export const MOCK_FEATURED_PRODUCTS: ProductListItem[] = [
  {
    id: 1,
    name: 'Voal Premium Signature Series',
    slug: 'voal-premium-signature-series',
    thumbnailUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80',
    price: 189000,
    comparePrice: 249000,
    ratingAverage: 4.9,
    totalReviews: 234,
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: false,
    category: BASE_CATEGORY,
    tags: ['premium', 'best-seller'],
  },
  {
    id: 2,
    name: 'Pashmina Silk Lavender Dream',
    slug: 'pashmina-silk-lavender-dream',
    thumbnailUrl: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80',
    price: 149000,
    comparePrice: 199000,
    ratingAverage: 4.8,
    totalReviews: 187,
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: true,
    category: { id: 5, name: 'Pashmina', slug: 'pashmina' },
    tags: ['new', 'trending'],
  },
  {
    id: 3,
    name: 'Bergo Instan Jersey Adem',
    slug: 'bergo-instan-jersey-adem',
    thumbnailUrl: 'https://images.unsplash.com/photo-1623119420099-1081b4da0b56?w=600&q=80',
    price: 89000,
    ratingAverage: 4.7,
    totalReviews: 312,
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: false,
    category: { id: 4, name: 'Bergo', slug: 'bergo' },
    tags: ['best-seller'],
  },
  {
    id: 4,
    name: 'Voal Motif Bunga Elegan',
    slug: 'voal-motif-bunga-elegan',
    thumbnailUrl: 'https://images.unsplash.com/photo-1603400521630-9f2de124b33b?w=600&q=80',
    price: 165000,
    comparePrice: 210000,
    ratingAverage: 4.6,
    totalReviews: 156,
    stockStatus: 'low_stock',
    isFeatured: true,
    isNew: true,
    category: BASE_CATEGORY,
    tags: ['new', 'limited'],
  },
  {
    id: 5,
    name: 'Gamis Kaftan Maxi Mewah',
    slug: 'gamis-kaftan-maxi-mewah',
    thumbnailUrl: 'https://images.unsplash.com/photo-1614251055880-ee96e4803393?w=600&q=80',
    price: 345000,
    comparePrice: 420000,
    ratingAverage: 4.9,
    totalReviews: 98,
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: false,
    category: { id: 2, name: 'Gamis', slug: 'gamis' },
    tags: ['premium', 'best-seller'],
  },
  {
    id: 6,
    name: 'Hijab Square Cotton Premium',
    slug: 'hijab-square-cotton-premium',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584592487914-a29c64f25887?w=600&q=80',
    price: 75000,
    ratingAverage: 4.5,
    totalReviews: 421,
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: false,
    category: BASE_CATEGORY,
    tags: ['best-seller', 'affordable'],
  },
  {
    id: 7,
    name: 'Mukena Travel Anti Kusut',
    slug: 'mukena-travel-anti-kusut',
    thumbnailUrl: 'https://images.unsplash.com/photo-1602532305019-3dbbd482dae9?w=600&q=80',
    price: 225000,
    comparePrice: 280000,
    ratingAverage: 4.8,
    totalReviews: 143,
    stockStatus: 'in_stock',
    isFeatured: true,
    isNew: true,
    category: { id: 3, name: 'Mukena', slug: 'mukena' },
    tags: ['new', 'travel'],
  },
  {
    id: 8,
    name: 'Voal Ceruti Shimmer Gold',
    slug: 'voal-ceruti-shimmer-gold',
    thumbnailUrl: 'https://images.unsplash.com/photo-1624378514195-7be76db3ac1c?w=600&q=80',
    price: 210000,
    comparePrice: 265000,
    flashSalePrice: 159000,
    flashSaleEndsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    ratingAverage: 4.7,
    totalReviews: 89,
    stockStatus: 'low_stock',
    isFeatured: true,
    isNew: false,
    category: BASE_CATEGORY,
    tags: ['flash-sale', 'premium'],
  },
];

export const MOCK_NEW_PRODUCTS: ProductListItem[] = [
  {
    id: 9,
    name: 'Voal Sifon Printing Bunga',
    slug: 'voal-sifon-printing-bunga',
    thumbnailUrl: 'https://images.unsplash.com/photo-1617083934551-ac87d28ff337?w=600&q=80',
    price: 135000,
    ratingAverage: 4.4,
    totalReviews: 32,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: BASE_CATEGORY,
  },
  {
    id: 10,
    name: 'Pashmina Diamond Monochrome',
    slug: 'pashmina-diamond-monochrome',
    thumbnailUrl: 'https://images.unsplash.com/photo-1622015663319-e97e697503ee?w=600&q=80',
    price: 175000,
    ratingAverage: 4.6,
    totalReviews: 21,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: { id: 5, name: 'Pashmina', slug: 'pashmina' },
  },
  {
    id: 11,
    name: 'Gamis Linen Premium Casual',
    slug: 'gamis-linen-premium-casual',
    thumbnailUrl: 'https://images.unsplash.com/photo-1631401953680-7bba22d21870?w=600&q=80',
    price: 289000,
    ratingAverage: 4.7,
    totalReviews: 15,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: { id: 2, name: 'Gamis', slug: 'gamis' },
  },
  {
    id: 12,
    name: 'Bergo Rempel Adem Stylish',
    slug: 'bergo-rempel-adem-stylish',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564694202779-bc908c327862?w=600&q=80',
    price: 115000,
    ratingAverage: 4.5,
    totalReviews: 28,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: { id: 4, name: 'Bergo', slug: 'bergo' },
  },
  {
    id: 13,
    name: 'Hijab Voal Laser Cut',
    slug: 'hijab-voal-laser-cut',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?w=600&q=80',
    price: 195000,
    comparePrice: 240000,
    ratingAverage: 4.8,
    totalReviews: 41,
    stockStatus: 'low_stock',
    isFeatured: false,
    isNew: true,
    category: BASE_CATEGORY,
  },
  {
    id: 14,
    name: 'Mukena Renda Premium Edition',
    slug: 'mukena-renda-premium-edition',
    thumbnailUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80',
    price: 310000,
    ratingAverage: 4.9,
    totalReviews: 12,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: { id: 3, name: 'Mukena', slug: 'mukena' },
  },
  {
    id: 15,
    name: 'Voal Crinkle Airflow',
    slug: 'voal-crinkle-airflow',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589156191108-c762ff4b96ab?w=600&q=80',
    price: 145000,
    ratingAverage: 4.5,
    totalReviews: 19,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: BASE_CATEGORY,
  },
  {
    id: 16,
    name: 'Aksesoris Brooch Emas',
    slug: 'aksesoris-brooch-emas',
    thumbnailUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80',
    price: 55000,
    ratingAverage: 4.3,
    totalReviews: 67,
    stockStatus: 'in_stock',
    isFeatured: false,
    isNew: true,
    category: { id: 6, name: 'Aksesoris', slug: 'aksesoris' },
  },
];

// ─── Flash Sale ───────────────────────────────────────────────────────────────

export const MOCK_FLASH_SALE: FlashSale = {
  id: 1,
  name: 'Flash Sale Siang Hari',
  startDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  endDate: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
  products: MOCK_FEATURED_PRODUCTS
    .filter((p) => p.flashSalePrice)
    .map((p) => ({
      id: p.id,
      product: p,
      originalPrice: p.comparePrice || p.price,
      flashSalePrice: p.flashSalePrice!,
      maxQty: 50,
      soldQty: Math.floor(Math.random() * 30) + 10,
    })),
};

// ─── Product Detail Mock ──────────────────────────────────────────────────────

export function getMockProductDetail(slug: string): ProductDetail | null {
  const found = [...MOCK_FEATURED_PRODUCTS, ...MOCK_NEW_PRODUCTS].find(
    (p) => p.slug === slug
  );
  if (!found) return null;

  return {
    ...found,
    description: `<p>Hadirkan keindahan dan kenyamanan dalam setiap langkah Anda dengan <strong>${found.name}</strong>. Dibuat dari material premium pilihan yang lembut di kulit dan nyaman dipakai sepanjang hari.</p><p>Dengan desain yang elegan dan modern, produk ini cocok untuk berbagai kesempatan — dari aktivitas sehari-hari hingga acara formal.</p><h3>Keunggulan Produk:</h3><ul><li>Material premium berkualitas tinggi</li><li>Tidak mudah kusut dan tahan lama</li><li>Tersedia dalam berbagai pilihan warna</li><li>Ukuran standar yang pas di semua tipe wajah</li><li>Mudah dibentuk sesuai selera</li></ul>`,
    shortDescription: `${found.name} — pilihan terbaik untuk penampilan Anda yang sempurna.`,
    specifications: {
      Material: 'Voal Premium Import',
      Ukuran: '115cm x 115cm',
      Berat: '150 gram',
      'Perawatan': 'Cuci tangan, jangan diperas',
      Garansi: '30 hari retur',
    },
    images: [
      { id: 1, url: found.thumbnailUrl, alt: found.name, isPrimary: true, sortOrder: 1 },
      { id: 2, url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80', alt: found.name, isPrimary: false, sortOrder: 2 },
      { id: 3, url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80', alt: found.name, isPrimary: false, sortOrder: 3 },
      { id: 4, url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80', alt: found.name, isPrimary: false, sortOrder: 4 },
    ],
    variants: [
      {
        id: 1,
        sku: `${slug.toUpperCase()}-PUTIH`,
        price: found.price,
        comparePrice: found.comparePrice,
        stock: 25,
        stockStatus: 'in_stock',
        options: [{ id: 1, name: 'Warna', value: 'Putih Tulang', colorHex: '#FAF8F1' }],
      },
      {
        id: 2,
        sku: `${slug.toUpperCase()}-NAVY`,
        price: found.price,
        comparePrice: found.comparePrice,
        stock: 12,
        stockStatus: 'low_stock',
        options: [{ id: 2, name: 'Warna', value: 'Navy Elegance', colorHex: '#1B2A4A' }],
      },
      {
        id: 3,
        sku: `${slug.toUpperCase()}-DUSTY`,
        price: found.price + 5000,
        comparePrice: found.comparePrice ? found.comparePrice + 5000 : undefined,
        stock: 0,
        stockStatus: 'out_of_stock',
        options: [{ id: 3, name: 'Warna', value: 'Dusty Rose', colorHex: '#D4A5A5' }],
      },
      {
        id: 4,
        sku: `${slug.toUpperCase()}-SAGE`,
        price: found.price,
        stock: 18,
        stockStatus: 'in_stock',
        options: [{ id: 4, name: 'Warna', value: 'Sage Green', colorHex: '#87A878' }],
      },
    ],
  };
}

// ─── All products (for listing page) ─────────────────────────────────────────

export const ALL_MOCK_PRODUCTS: ProductListItem[] = [
  ...MOCK_FEATURED_PRODUCTS,
  ...MOCK_NEW_PRODUCTS,
];
